In [ ]:
import numpy as np
import pandas as pd # to read dataset
import warnings # to remove warnings
warnings.filterwarnings('ignore')

# Loading first dataset

In [ ]:
first_dataset = pd.read_csv('/content/dataset.csv')
first_dataset

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [ ]:
second_dataset = pd.read_csv('/content/IPL Matches 2008-2020.csv')
second_dataset

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

# Data cleaning

In [ ]:
# finding total runs scored in each innings
total_runs = first_dataset.groupby(['match_id','inning']).sum()['total_runs'].add(1).reset_index()
total_runs

      match_id  inning  total_runs
0            1       1         208
1            1       2         173
2            2       1         185
3            2       2         188
4            3       1         184
...        ...     ...         ...
1523     11413       2         171
1524     11414       1         156
1525     11414       2         163
1526     11415       1         153
1527     11415       2         158

[1528 rows x 3 columns]

In [ ]:
# selecting only first innings score to find target of each match
total_runs = total_runs[total_runs['inning'] == 1]
total_runs

      match_id  inning  total_runs
0            1       1         208
2            2       1         185
4            3       1         184
6            4       1         164
8            5       1         158
...        ...     ...         ...
1518     11347       1         144
1520     11412       1         137
1522     11413       1         172
1524     11414       1         156
1526     11415       1         153

[756 rows x 3 columns]

In [ ]:
# merging the total row columns based on match_id
match_df = second_dataset.merge(total_runs[['match_id','total_runs']],left_on='id',right_on='match_id')

In [ ]:
match_df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,208
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,185
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,184
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,164
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,144
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,137
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,172
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,156
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,153

In [ ]:
# for final dataset selecting only these columns
match_df = match_df[['id','city','winner','total_runs']]

In [ ]:
match_df = match_df.rename(columns={'id':'match_id'})

In [ ]:
second_innings = match_df.merge(first_dataset, on='match_id')
second_innings

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
0,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,Hyderabad,Sunrisers Hyderabad,208,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [ ]:
# here we will be predicting the winner shape is 86240 and 24 col
# but 24 col are to much we only want 9 or 10 rows
second_innings  = second_innings[second_innings['inning'] == 2]
second_innings.shape

(86240, 24)

In [ ]:
second_innings['batting_team'].value_counts()

batting_team
Kolkata Knight Riders          10728
Royal Challengers Bangalore    10605
Mumbai Indians                 10033
Delhi Daredevils               10027
Kings XI Punjab                 9801
Rajasthan Royals                9043
Chennai Super Kings             8783
Sunrisers Hyderabad             5131
Deccan Chargers                 3754
Pune Warriors                   2995
Gujarat Lions                   1832
Delhi Capitals                  1165
Rising Pune Supergiant           906
Rising Pune Supergiants          731
Kochi Tuskers Kerala             706
Name: count, dtype: int64

In [ ]:
second_innings['batting_team'] = second_innings['batting_team'].replace('Delhi Daredevils','Delhi Capitals')
second_innings['bowling_team'] = second_innings['bowling_team'].replace('Delhi Daredevils','Delhi Capitals')

second_innings['batting_team'] = second_innings['batting_team'].replace('Deccan Chargers','Sunrisers Hyderabad')
second_innings['bowling_team'] = second_innings['bowling_team'].replace('Deccan Chargers','Sunrisers Hyderabad')

In [ ]:
second_innings['batting_team'].value_counts()

batting_team
Delhi Capitals                 11192
Kolkata Knight Riders          10728
Royal Challengers Bangalore    10605
Mumbai Indians                 10033
Kings XI Punjab                 9801
Rajasthan Royals                9043
Sunrisers Hyderabad             8885
Chennai Super Kings             8783
Pune Warriors                   2995
Gujarat Lions                   1832
Rising Pune Supergiant           906
Rising Pune Supergiants          731
Kochi Tuskers Kerala             706
Name: count, dtype: int64

In [ ]:
second_innings['bowling_team'].value_counts()

bowling_team
Sunrisers Hyderabad            12268
Mumbai Indians                 11874
Kings XI Punjab                10347
Chennai Super Kings            10339
Royal Challengers Bangalore     9704
Kolkata Knight Riders           9264
Delhi Capitals                  8506
Rajasthan Royals                7574
Pune Warriors                   2311
Gujarat Lions                   1570
Rising Pune Supergiant           966
Kochi Tuskers Kerala             774
Rising Pune Supergiants          743
Name: count, dtype: int64

In [ ]:
teams = ['Kolkata Knight Riders',
         'Chennai Super Kings',
         'Kings XI Punjab',
         'Rajasthan Royals',
         'Mumbai Indians',
         'Delhi Capitals',
         'Royal Challengers Bangalore',
         'Sunrisers Hyderabad']

In [ ]:
second_innings = second_innings[second_innings['batting_team'].isin(teams)]
second_innings = second_innings[second_innings['bowling_team'].isin(teams)]
# remove all data except these 8 teams using isin function
# so isin func simply check that the team name among this list or not if
# it is not in that list it will simply exclude that row and if it is in the
# list it will consider the row

now we will find the current score of the dataset but in dataset there is no such column present but using the column
total_runs_y we can find the current score using the cumulative solve function

this column store runs made by batsman at particular at particular ball so to calulate after each ball we will use a concept called as cumulative sum we just go on adding adding and after at the end we just get the total sum of column so we will use the same concept here.

In [ ]:
# Finding current score using cumulative sum function
second_innings['current_Score'] = second_innings.groupby('match_id')['total_runs_y'].cumsum()
second_innings
# This approach is applied after the groupby operation to calculate the cumulative sum specifically for that column.

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_Score
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,1,0,1,NaN,NaN,NaN,1
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,1
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,0,NaN,NaN,NaN,1
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,0,2,0,2,NaN,NaN,NaN,3
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,0,4,0,4,NaN,NaN,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,0,0,1,0,1,NaN,NaN,NaN,152
179074,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,0,0,2,0,2,NaN,NaN,NaN,154
179075,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,0,0,1,0,1,SR Watson,run out,KH Pandya,155
179076,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,0,0,2,0,2,NaN,NaN,NaN,157
179077,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,0,0,SN Thakur,lbw,NaN,157

In [ ]:
 # calculation of runs left
 second_innings['runs_left'] = second_innings['total_runs_x'] - second_innings['current_Score']
 second_innings
 # total_run = 208 - currentscore(1) = run_left = 207

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_Score,runs_left
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,1,0,1,NaN,NaN,NaN,1,207
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,NaN,NaN,NaN,1,207
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,NaN,NaN,NaN,1,207
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,2,0,2,NaN,NaN,NaN,3,205
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,4,0,4,NaN,NaN,NaN,7,201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,0,1,0,1,NaN,NaN,NaN,152,1
179074,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,0,2,0,2,NaN,NaN,NaN,154,-1
179075,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,0,1,0,1,SR Watson,run out,KH Pandya,155,-2
179076,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,0,2,0,2,NaN,NaN,NaN,157,-4
179077,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,0,SN Thakur,lbw,NaN,157,-4

In [ ]:
#calulating ball left after each ball is thrown
second_innings['balls_left'] = 126 - (second_innings['over']*6 + second_innings['ball'])
second_innings
# dervied from the total no of balls in innings - no of balls already played

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_Score,runs_left,balls_left
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,1,0,1,NaN,NaN,NaN,1,207,119
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,207,118
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,207,117
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,2,0,2,NaN,NaN,NaN,3,205,116
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,4,0,4,NaN,NaN,NaN,7,201,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,1,0,1,NaN,NaN,NaN,152,1,4
179074,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,2,0,2,NaN,NaN,NaN,154,-1,3
179075,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,1,0,1,SR Watson,run out,KH Pandya,155,-2,2
179076,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,2,0,2,NaN,NaN,NaN,157,-4,1
179077,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,SN Thakur,lbw,NaN,157,-4,0

# Getting wickets

In [ ]:
#player_dismissed tell if batsmen was out or not while playing that ball
#fill null value with 0
second_innings['player_dismissed'] = second_innings['player_dismissed'].fillna("0")

#if column value is not zero mark it 1
second_innings['player_dismissed'] = second_innings['player_dismissed'].apply(lambda x:x if x == "0" else "1")

#changing datatype of column  name
second_innings['player_dismissed'] = second_innings['player_dismissed'].astype('int')

#finding wickets using cumulative sum function
wickets = second_innings.groupby('match_id')['player_dismissed'].cumsum()

#calculating wickets left by simple maths operations
second_innings['wickets'] = 10 - wickets
second_innings

#

#

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_Score,runs_left,balls_left,wickets
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,1,0,1,0,NaN,NaN,1,207,119,10
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,207,118,10
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,207,117,10
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,2,0,2,0,NaN,NaN,3,205,116,10
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,4,0,4,0,NaN,NaN,7,201,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,1,0,1,0,NaN,NaN,152,1,4,5
179074,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,2,0,2,0,NaN,NaN,154,-1,3,5
179075,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,1,0,1,1,run out,KH Pandya,155,-2,2,4
179076,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,2,0,2,0,NaN,NaN,157,-4,1,4
179077,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,1,lbw,NaN,157,-4,0,3

# Current Runrate

In [ ]:
#CRR formula
second_innings['crr'] = (second_innings['current_Score']*6)/(120 - second_innings['balls_left'])
second_innings['crr'] = second_innings['crr'].round(2)  # Round to 2 decimal places
second_innings

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,player_dismissed,dismissal_kind,fielder,current_Score,runs_left,balls_left,wickets,crr,rrr,results
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,NaN,NaN,1,207,119,10,6.00,10.44,0
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,NaN,NaN,1,207,118,10,3.00,10.53,0
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,NaN,NaN,1,207,117,10,2.00,10.62,0
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,NaN,NaN,3,205,116,10,4.50,10.60,0
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,NaN,NaN,7,201,115,10,8.40,10.49,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,NaN,NaN,152,1,4,5,7.86,1.50,0
179074,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,NaN,NaN,154,-1,3,5,7.90,-2.00,0
179075,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,1,run out,KH Pandya,155,-2,2,4,7.88,-6.00,0
179076,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,NaN,NaN,157,-4,1,4,7.92,-24.00,0
179077,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,1,lbw,NaN,157,-4,0,3,7.85,-inf,0

# Required Runrate

In [ ]:
# rrr formula
second_innings['rrr'] = round((second_innings['runs_left']*6)/(second_innings['balls_left']),2)
second_innings
# runsleft / overleft
# using round func rounded the answer upto 2 decimal places

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,player_dismissed,dismissal_kind,fielder,current_Score,runs_left,balls_left,wickets,crr,rrr,results
125,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,NaN,NaN,1,207,119,10,6.00,10.44,0
126,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,NaN,NaN,1,207,118,10,3.00,10.53,0
127,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,NaN,NaN,1,207,117,10,2.00,10.62,0
128,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,NaN,NaN,3,205,116,10,4.50,10.60,0
129,1,Hyderabad,Sunrisers Hyderabad,208,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,NaN,NaN,7,201,115,10,8.40,10.49,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,NaN,NaN,152,1,4,5,7.86,1.50,0
179074,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,NaN,NaN,154,-1,3,5,7.90,-2.00,0
179075,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,1,run out,KH Pandya,155,-2,2,4,7.88,-6.00,0
179076,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,NaN,NaN,157,-4,1,4,7.92,-24.00,0
179077,11415,Hyderabad,Mumbai Indians,153,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,1,lbw,NaN,157,-4,0,3,7.85,-inf,0

In [ ]:
# function to mark winner team 0 or 1 based on winner column
def winner(team):
    return 1 if team['batting_team'] == team['winner'] else 0

In [ ]:
second_innings['results'] = second_innings.apply(winner,axis=1)
second_innings.sample(10)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,player_dismissed,dismissal_kind,fielder,current_Score,runs_left,balls_left,wickets,crr,rrr,results
29686,128,Durban,Deccan Chargers,169,2,Mumbai Indians,Sunrisers Hyderabad,5,3,SR Tendulkar,...,0,NaN,NaN,37,132,93,9,8.222222,8.52,0
75387,320,Chennai,Chennai Super Kings,206,2,Chennai Super Kings,Royal Challengers Bangalore,2,6,M Vijay,...,0,NaN,NaN,7,199,108,10,3.500000,11.06,1
156019,7917,Bengaluru,Chennai Super Kings,214,2,Chennai Super Kings,Royal Challengers Bangalore,3,1,SK Raina,...,0,NaN,NaN,11,203,107,9,5.076923,11.38,1
165597,11140,Jaipur,Kings XI Punjab,201,2,Rajasthan Royals,Kings XI Punjab,3,4,JC Buttler,...,0,NaN,NaN,27,174,104,10,10.125000,10.04,0
131310,554,Chennai,Chennai Super Kings,149,2,Royal Challengers Bangalore,Chennai Super Kings,2,1,V Kohli,...,0,NaN,NaN,4,145,113,10,3.428571,7.70,0
30744,132,Port Elizabeth,Mumbai Indians,188,2,Kolkata Knight Riders,Mumbai Indians,15,3,LR Shukla,...,0,NaN,NaN,91,97,33,4,6.275862,17.64,0
155398,7914,Jaipur,Rajasthan Royals,173,2,Rajasthan Royals,Mumbai Indians,20,1,J Archer,...,1,caught,HH Pandya,164,9,5,3,8.556522,10.80,1
138129,584,Hyderabad,Kolkata Knight Riders,143,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,G Gambhir,...,0,NaN,NaN,56,87,67,10,6.339623,7.79,1
72453,307,Chennai,Chennai Super Kings,206,2,Royal Challengers Bangalore,Chennai Super Kings,18,5,Z Khan,...,0,NaN,NaN,126,80,13,3,7.065421,36.92,0
57561,243,Chandigarh,Kings XI Punjab,189,2,Kings XI Punjab,Chennai Super Kings,19,3,PC Valthaty,...,0,NaN,NaN,183,6,9,6,9.891892,4.00,1

# Only taking required columns

In [ ]:
required_data = second_innings[['batting_team','bowling_team','city','runs_left','balls_left','wickets','total_runs_x','crr','rrr','results']]
required_data

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr,results
125,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,119,10,208,6.00,10.44,0
126,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,118,10,208,3.00,10.53,0
127,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,207,117,10,208,2.00,10.62,0
128,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,205,116,10,208,4.50,10.60,0
129,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,201,115,10,208,8.40,10.49,0
...,...,...,...,...,...,...,...,...,...,...
179073,Chennai Super Kings,Mumbai Indians,Hyderabad,1,4,5,153,7.86,1.50,0
179074,Chennai Super Kings,Mumbai Indians,Hyderabad,-1,3,5,153,7.90,-2.00,0
179075,Chennai Super Kings,Mumbai Indians,Hyderabad,-2,2,4,153,7.88,-6.00,0
179076,Chennai Super Kings,Mumbai Indians,Hyderabad,-4,1,4,153,7.92,-24.00,0
179077,Chennai Super Kings,Mumbai Indians,Hyderabad,-4,0,3,153,7.85,-inf,0

# Sampling Data

In [ ]:
#sampling dataset for proper model building so that our model will be more
# accurate
final_data = required_data.sample(required_data.shape[0])

# Dropping NULL values

In [ ]:
final_data.dropna(inplace=True)

# Removing rows where ball_left=0 to reomve -inf and inf from rrr column

In [ ]:
# tha value in minus not suitable for model building
# it simply remove the rows from our final dataset where the ball left is zero
final_data = final_data[final_data['balls_left'] != 0]

# Storing data in new csv

In [ ]:
final_data.to_csv('final_data.csv',index=False)

# Building Model

In [ ]:
from sklearn.model_selection import train_test_split as tts

In [ ]:
x = final_data.iloc[:, :-1]
y = final_data.iloc[:,-1]
# result column in y variable
# remainig all column in X variable

In [ ]:
x_train,x_test,y_train,y_test = tts(x,y,test_size=0.25,random_state=100)
x_train
# train , test and split

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr
22736,Rajasthan Royals,Kings XI Punjab,Chandigarh,139,52,7,222,7.32,16.04
159206,Kolkata Knight Riders,Mumbai Indians,Mumbai,63,34,6,188,8.72,11.12
35029,Delhi Capitals,Mumbai Indians,East London,75,70,9,117,5.04,6.43
27046,Chennai Super Kings,Kings XI Punjab,Mumbai,74,83,9,113,6.32,5.35
14050,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,177,61,3,223,4.68,17.41
...,...,...,...,...,...,...,...,...,...
120057,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata,148,75,9,196,6.40,11.84
100777,Kings XI Punjab,Chennai Super Kings,Chennai,168,98,9,187,5.18,10.29
20214,Mumbai Indians,Rajasthan Royals,Mumbai,14,37,7,104,6.51,2.27
11803,Mumbai Indians,Kings XI Punjab,Mumbai,110,44,6,231,9.55,15.00
149139,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata,157,104,10,172,5.62,9.06

In [ ]:
# test_data
x_test

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr
118061,Delhi Capitals,Rajasthan Royals,Ahmedabad,184,109,10,202,9.82,10.13
154659,Kings XI Punjab,Kolkata Knight Riders,Kolkata,98,66,10,201,11.44,8.91
23759,Sunrisers Hyderabad,Mumbai Indians,Hyderabad,92,38,6,179,6.37,14.53
74708,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,146,85,7,166,3.43,10.31
69067,Mumbai Indians,Sunrisers Hyderabad,Mumbai,82,53,7,136,4.84,9.28
...,...,...,...,...,...,...,...,...,...
44973,Mumbai Indians,Kolkata Knight Riders,Mumbai,125,100,10,156,9.30,7.50
36007,Delhi Capitals,Kolkata Knight Riders,Johannesburg,67,75,9,124,7.60,5.36
159369,Kings XI Punjab,Rajasthan Royals,Indore,159,112,10,161,1.50,8.52
128420,Sunrisers Hyderabad,Mumbai Indians,Mumbai,149,113,10,158,7.71,7.91
160653,Rajasthan Royals,Chennai Super Kings,Jaipur,73,37,6,189,8.39,11.84

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# using oneHotEncoder for making textual columns to numerical column for model
# building
# The 'sparse' argument has been replaced with 'sparse_output' in newer versions of scikit-learn.
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])
],
remainder='passthrough') #passthrough confirms that no other column were touch
# during this process

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
# creating pipeline (building model)
pipe = pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [ ]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [ ]:
y_pred = pipe.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8157232015766999

In [ ]:
pipe.predict_proba(x_test)[0]

array([0.99540035, 0.00459965])

In [ ]:
pipe.predict_proba(x_test)[0]

array([0.99540035, 0.00459965])

In [ ]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [ ]:
final_data['city'].unique()

array(['Johannesburg', 'Chandigarh', 'Kolkata', 'Delhi', 'Jaipur',
       'Mumbai', 'Cuttack', 'Hyderabad', 'Chennai', 'Durban', 'Abu Dhabi',
       'Pune', 'Raipur', 'Bangalore', 'Visakhapatnam', 'Ahmedabad',
       'Bengaluru', 'Port Elizabeth', 'Indore', 'Mohali', 'Centurion',
       'Dharamsala', 'Bloemfontein', 'East London', 'Kimberley', 'Ranchi',
       'Cape Town', 'Sharjah', 'Nagpur', nan], dtype=object)

# Random Forest classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city']) # Change 'sparse' to 'sparse_output'
],
remainder='passthrough')

pipe = Pipeline([
    ('step1',trf),
    ('step2',RandomForestClassifier())
])

pipe.fit(x_train,y_train)

y_pred = pipe.predict(x_test)

accuracy_score(y_test,y_pred)

0.9986860834337019

In [ ]:
pipe.predict_proba(x_test)[0]

In [ ]:
pipe.predict_proba(x_test)[0]
array([1., 0.])
pickle.dump(pipe,open('pipe2.pkl','wb'))